#--------- Generic stuff all our Dockerfiles should start with so we get caching ------------
FROM ubuntu:14.04
MAINTAINER Ido Shamon

# Configuring locales
ENV DEBIAN_FRONTEND noninteractive
RUN dpkg-reconfigure locales && \
      locale-gen en_US.UTF-8 && \
      update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update && apt-get install -y \
        software-properties-common python-software-properties \
        vim build-essential autoconf git

#-------------Application Specific Stuff ----------------------------------------------------

RUN add-apt-repository ppa:cartodb/postgresql-9.3 && \
    add-apt-repository ppa:cartodb/gis && \
    apt-get update
RUN apt-get install -y -q \
    postgresql-9.3 \
    postgresql-client-9.3 \
    postgresql-contrib-9.3 \
    postgresql-server-dev-9.3 \
    postgresql-plpython-9.3 \
    postgresql-9.3-plproxy \
    postgresql-9.3-postgis-2.1 \
    postgresql-9.3-postgis-2.1-scripts \
    postgis \
    pgtune

# auth configuration
ADD ./auth-configuration.sh /tmp/auth-configuration.sh
RUN chmod 0755 /tmp/auth-configuration.sh
RUN /tmp/auth-configuration.sh

# Setting PostgreSQL
RUN rm /etc/postgresql/9.3/main/pg_hba.conf
ADD ./pg_hba.conf /etc/postgresql/9.3/main/

RUN apt-get install -y proj proj-bin proj-data libproj-dev
RUN apt-get install -y libjson0 libjson0-dev python-simplejson
RUN apt-get install -y libgeos-c1v5 libgeos-dev
RUN apt-get install -y gdal-bin libgdal1-dev libgdal-dev
RUN apt-get install -y ogr2ogr2-static-bin

RUN apt-get install -y libxml2-dev
RUN apt-get install -y liblwgeom-2.1.8 postgis postgresql-9.3-postgis-2.2 postgresql-9.3-postgis-scripts

RUN apt-get install -y netcat
#---------------------------------------------------------------------------------------------

# Open port 5432 so linked containers can see them
EXPOSE 5432

# We will RUN any commands in this when the container starts
ADD start-postgis.sh /start-postgis.sh
RUN chmod 0755 /start-postgis.sh

CMD /start-postgis.sh
