FROM ubuntu:14.04
MAINTAINER Ido Shamon

ENV  DEBIAN_FRONTEND noninteractive

RUN cd /home && git clone git://github.com/CartoDB/CartoDB-SQL-API.git
RUN cd /home/CartoDB-SQL-API && ./configure

RUN apt-get update && \
      useradd -m -d /home/cartodb -s /bin/bash cartodb && \
      apt-get install -y -q software-properties-common && \
      add-apt-repository -y ppa:chris-lea/node.js && \
      apt-get update
RUN apt-get install -y nodejs git make g++
RUN apt-get install -y libjson0 libjson0-dev python-simplejson

RUN apt-get install -y -q libgeos-c1 \
      libgeos-dev libjson0 python-simplejson libjson0-dev proj-bin \
      proj-data libproj-dev \
      gdal-bin libgdal1-dev \
      python-setuptools \
      varnish imagemagick libmapnik-dev \
      python-mapnik mapnik-utils postgis \
      python-argparse python-gdal python-chardet openssl libreadline6 curl \
      libc6-dev ncurses-dev automake libtool bison subversion \
      pkg-config libpq5 libpq-dev libcurl4-gnutls-dev libffi-dev \
      libgdbm-dev gnupg libreadline6-dev 
RUN cd /home/CartoDB-SQL-API && npm install

COPY entry-point.sh /home
RUN chmod 700 /home/entry-point.sh
ENTRY [/home/entry-point.sh]
