#!/bin/sh

if test -n "$1"; then
        SUBDOMAIN="$1"
else
        echo -n "Enter a subdomain: "; read SUBDOMAIN
fi

if test -n "$2"; then
        PASSWORD="$2"
else
        echo -n "Enter a password (cleartext!): "; read PASSWORD
fi

if test -n "$3"; then
        EMAIL="$3"
else
        echo -n "Enter an email: "; read EMAIL
fi

echo "--- setup admin user"
RAILS_ENV=development bundle exec rake cartodb:db:setup_user --trace SUBDOMAIN="${SUBDOMAIN}" \
        PASSWORD="${PASSWORD}" \
        EMAIL="${EMAIL}"
if test $? -ne 0; then exit 1; fi

#SUBDOMAIN="setup_user"
#PASSWORD="cartodb3"
#ADMIN_PASSWORD="cartodb3"
#EMAIL="sabalah21gmail.com"
#
#echo "--- Creating setup user"
#bundle exec rake cartodb:db:create_setup_user --trace SUBDOMAIN="${SUBDOMAIN}" \
#        PASSWORD="${PASSWORD}" \
#        EMAIL="${EMAIL}"
#
#echo "--- Creating databases"
#bundle exec rake cartodb:db:setup --trace SUBDOMAIN="${SUBDOMAIN}" \
#	PASSWORD="${PASSWORD}" ADMIN_PASSWORD="${ADMIN_PASSWORD}" \
#	EMAIL="${EMAIL}"
#if test $? -ne 0; then exit 1; fi
#
## # Update your quota to 100GB
#echo "--- Updating quota to 100GB"
#bundle exec rake cartodb:db:set_user_quota["${SUBDOMAIN}",102400]
#if test $? -ne 0; then exit 1; fi
#
## # Allow unlimited tables to be created
#echo "--- Allowing unlimited tables creation"
#bundle exec rake cartodb:db:set_unlimited_table_quota["${SUBDOMAIN}"]
#if test $? -ne 0; then exit 1; fi
#
## # Allow user to create private tables in addition to public
#echo "--- Allowing private tables creation"
#bundle exec rake cartodb:db:set_user_private_tables_enabled["${SUBDOMAIN}",'true']
# if test $? -ne 0; then exit 1; fi
#
## # Set the account type
#echo "--- Setting cartodb account type"
#bundle exec rake cartodb:db:set_user_account_type["${SUBDOMAIN}",'[DEDICATED]']
#if test $? -ne 0; then exit 1; fi
